steps:
  - label: gittag
    command: scripts/write-git-version
    timeout_in_minutes: 1
    concurrency: 1
    concurrency_group: "link-mobile-observations"
    artifact_paths: git-version.txt
    agents:
      - queue=link-aws-dev

  - label: Upload docker image
    command: scripts/write-git-version
    timeout_in_minutes: 10
    concurrency: 1
    concurrency_group: "link-mobile-observations"
    agents:
      - queue=link-scala-dev-nyc
    command:
      - scripts/package-swarm
  - label: dev ds deploy
    timeout_in_minutes: 5
    concurrency: 1
    concurrency_group: "link-mobile-observations"
    command:
      - scripts/deploy-swarm
#    branches: master
    agents:
      - queue=link-aws-dev
    env:
      APPNAME: link-mobile-observations