steps:
  - label: Upload docker image
    timeout_in_minutes: 10
    concurrency: 1
    concurrency_group: "link-mobile-observations"
    agents:
      - queue=link-scala-dev-nyc
    command:
      - scripts/package-swarm

  - block: dev

  - label: dev ds deploy
    timeout_in_minutes: 5
    concurrency: 1
    concurrency_group: "link-mobile-observations"
    command:
      - scripts/deploy-swarm
#    branches: master
    agents:
      - queue=link-aws-dev
    env:
      APPNAME: link-mobile-observations
      LINK_ENV: dev

  - block: qa

  - label: QA ds deploy
    timeout_in_minutes: 5
    concurrency: 1
    concurrency_group: "link-mobile-observations"
    command:
      - scripts/deploy-swarm
#    branches: master
    agents:
      - queue=link-aws-dev
    env:
      APPNAME: link-mobile-observations
      LINK_ENV: qa