---
- name: Upload
  hosts: localhost
  tasks:
    - name: Log into Docker Hub
      docker_login:
        username: '{{ docker_user }}'
        password: '{{ docker_password }}'
        email: '{{ docker_email }}'
    - name: Upload image
      docker_image:
        name: "intersection"
        repository: "intersection/link-mobile-observations"
        tag: "<TAG>"
        state: present
        push: yes
        pull: no
    - name: Log out of Docker Hub
      docker_login:
        state: absent
